Demo1/routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Route::resource('productos', 'ProductoController');

Demo1/app/Producto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Producto extends Model
{
	protected $fillable = [
		'nombre',
		'precio',
		'cantidad'
	];
}

Demo1/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

Demo1/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

Demo1/app/Http/Controllers/ProductoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Producto;

class ProductoController extends Controller
{

    public function index(){
        $productos = Producto::all();

        return view('productos.index', compact('productos'));
    }

    public function create(){
        return view('productos.create');
    }

    public function store(Request $request){
      $request->validate([
        'nombre'=>'required',
        'precio'=> 'required|integer',
        'cantidad' => 'required|integer'
      ]);
      $producto = new Producto([
        'nombre' => $request->get('nombre'),
        'precio'=> $request->get('precio'),
        'cantidad'=> $request->get('cantidad')
      ]);
      $producto->save();
      return redirect('/productos')->with('success', 'Producto agregado');
    }

    public function show($id){
        //
    }

    public function edit($id){
        $producto = Producto::find($id);

        return view('productos.edit', compact('producto'));
    }

    public function update(Request $request, $id){
      $request->validate([
        'nombre'=>'required',
        'precio'=> 'required|integer',
        'cantidad' => 'required|integer'
      ]);

      $producto = Producto::find($id);
      $producto->nombre = $request->get('nombre');
      $producto->precio = $request->get('precio');
      $producto->cantidad = $request->get('cantidad');
      $producto->save();

      return redirect('/productos')->with('success', 'Producto actualizado');
    }

    public function destroy($id){
        $producto = Producto::find($id);
        $producto->delete();

      return redirect('/productos')->with('success', 'Producto eliminado');
    }
}

Demo1/resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Productos</title>
  <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
</head>
<body>
  <div class="container">
    @yield('content')
  </div>
  <script src="{{ asset('js/app.js') }}" type="text/js"></script>
</body>
</html>

Demo1/resources/views/productos/create.blade.php
@extends('layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Agregar producto
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('productos.store') }}">
          <div class="form-group">
              {{ csrf_field() }}
              <label for="nombre">Nombre:</label>
              <input type="text" class="form-control" name="nombre"/>
          </div>
          <div class="form-group">
              <label for="precio">Precio:</label>
              <input type="text" class="form-control" name="precio"/>
          </div>
          <div class="form-group">
              <label for="cantidad">Cantidad:</label>
              <input type="text" class="form-control" name="cantidad"/>
          </div>
          <button type="submit" class="btn btn-primary">Agregar</button>
      </form>
  </div>
</div>
@endsection

Demo1/resources/views/productos/edit.blade.php
@extends('layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Editar Producto
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('productos.update', $producto->id) }}">
        @method('PATCH')
        @csrf
        <div class="form-group">
          <label for="nombre">Nombre:</label>
          <input type="text" class="form-control" name="nombre" value={{ $producto->nombre }} />
        </div>
        <div class="form-group">
          <label for="precio">Precio:</label>
          <input type="text" class="form-control" name="precio" value={{ $producto->precio }} />
        </div>
        <div class="form-group">
          <label for="cantidad">Calidad:</label>
          <input type="text" class="form-control" name="cantidad" value={{ $producto->cantidad }} />
        </div>
        <button type="submit" class="btn btn-primary">Actualizar</button>
      </form>
  </div>
</div>
@endsection

Demo1/resources/views/productos/index.blade.php
@extends('layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>NOMBRE</td>
          <td>PRECIO</td>
          <td>CANTIDAD</td>
          <td colspan="2">ACCION</td>
        </tr>
    </thead>
    <tbody>
        @foreach($productos as $producto)
        <tr>
            <td>{{$producto->id}}</td>
            <td>{{$producto->nombre}}</td>
            <td>{{$producto->precio}}</td>
            <td>{{$producto->cantidad}}</td>
            <td><a href="{{ route('productos.edit',$producto->id)}}" class="btn btn-primary">Editar</a></td>
            <td>
                <form action="{{ route('productos.destroy', $producto->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Eliminar</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
@endsection